### ISSUE TITLE
Automate maintaining of static rendering of notebooks

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#11]
The notebooks are statically rendered on github.io (e.g. https://nasa-navo.github.io/navo-workshop/UseCase_I.html), but updating those static views is a manual process.  Either automate that process, or at least improve the manual process by documenting it and possibly adding supporting scripts.

**Comment by eteq** [comment]
We might want to use this machinery for that purpose: https://github.com/spacetelescope/nbcollection . That work is derived from the astropy machinery, and the goal is eventually to feed it back into https://github.com/astropy/nbcollection (but on an ambiguous timescale, and the one in the spacetelescope fork is definitely more up-to-date).

**Comment by tomdonaldson** [comment]
If somehow this can't be done.  Refresh the static version by 6/1/21.

**Comment by tomdonaldson** [comment]
@tomdonaldson to refresh the static content by Monday, 5/24.

**Comment by tomdonaldson** [comment]
I tried generating the html using `nbcollection` (both astropy and spacetelescope versions), and found that it didn't work out of the box, the complaint shown below:
```
(build_static):$ nbcollection convert .
[nbcollection (INFO)]: Collected 10 notebook files
[nbcollection (INFO)]: Finished running notebook 'CS_Spectral_Access.ipynb' (26.25 seconds) ✅
Traceback (most recent call last):
  File "/Users/donald/opt/anaconda3/envs/build_static/bin/nbcollection", line 8, in <module>
    sys.exit(main())
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbcollection/__main__.py", line 33, in main
    commands[parsed.command](args)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbcollection/commands/convert.py", line 34, in convert
    nbcollection.convert()
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbcollection/converter.py", line 154, in convert
    nb.convert()
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbcollection/notebook.py", line 147, in convert
    resources=resources)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 148, in template
    self._template_cached = self._load_template()
  File "/Users/donald/opt/anaconda3/envs/build_static/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 347, in _load_template
    raise ValueError("No template_file specified!")
ValueError: No template_file specified!
```
I left this task until the last minute, so while I suspect that this exception is simple to work around or with, I chose to not use `nbcollection` for this iteration, instead using `jupyter nbconvert --execute --to html *.ipynb`.

This is now wrapped in a script in https://github.com/NASA-NAVO/NASA-NAVO.github.io/tree/main/workshop-notebooks, along with a manually-created `index.html`.  All the content is then available at: https://nasa-navo.github.io/workshop-notebooks/

**Comment by bsipocz** [comment]
Done in #62
